version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Spring Boot App
          command: |
            echo "Building Springmart Backend"
            mvn -B -DskipTests clean package
            docker build -t justenmx/springmart-backend .

  test:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            echo "Running tests"
            mvn test

  scan:
    docker:
      - image: cimg/openjdk:17.0.8
    environment:
      IMAGE_NAME: justenmx/springmart-backend:latest
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME

workflows:
  ci_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
