version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Checkout Private Repo
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone git@github.com:JustenMX/ntu-project2-springmart-backend.git
      - run:
          name: Build Springmart Backend
          command: |
            echo "Building Springmart Backend"
            mvn -B -DskipTests clean package
            docker build -t justenmx/springmart-backend .

  test:
    docker:
      - image: cimg/openjdk:17.0.8
    # environment:
    #   DB_HOST: psql-db
    #   DB_PORT: 5432
    #   DB_NAME: springmart
    #   DB_USER: justen
    #   DB_PASSWORD: OzCq4KoMRSzgvGAn
    steps:
      - checkout
      - run:
          name: Debug Connection
          command: |
            echo "Database Host: $DB_HOST"
            echo "Database Port: $DB_PORT"
            echo "Database Name: $DB_NAME"
            echo "Database User: $DB_USER"
            echo "Database Password: $DB_PASSWORD"
      - run:
          name: Run Unit Tests
          command: |
            echo "Running tests"
            mvn -B test
      - store_test_results:
          path: target/surefire-reports

  scan:
    docker:
      - image: cimg/openjdk:17.0.8
    environment:
      IMAGE_NAME: justenmx/springmart-backend:latest
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME

workflows:
  springmart_backend_ci_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
