version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@2.4.0
  snyk: snyk/snyk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: postgres:latest
        environment:
          POSTGRES_DB: springmart
          POSTGRES_USER: justen
          # POSTGRES_PASSWORD: your_password_here

    steps:
      - checkout
      - maven/test
      - run:
          name: Echo Message
          command: echo "Running Build"
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

  test:
    docker:
      - image: cimg/openjdk:17.0
      - image: postgres:latest
        environment:
          POSTGRES_DB: springmart
          POSTGRES_USER: justen
          # POSTGRES_PASSWORD: your_password_here

    steps:
      - checkout
      - maven/test
      - run:
          name: Echo Message
          command: echo "Running Tests"
      - run:
          name: Test
          command: mvn test

  build-and-push:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: justenmx/springmart-backend
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: justenmx/springmart-backend
          tag: <<pipeline.git.tag>>

  scan:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      IMAGE_NAME: justenmx/springmart-backend

    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  SpringMartBackendPipeline:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - build-and-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - scan:
          requires:
            - build
