version: 2.1

orbs:
  maven: circleci/maven@1.4.1

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:17.0.8
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: justen
          POSTGRES_DB: springmart
          POSTGRES_HOST_AUTH_METHOD: trust

workflows:
  build-and-deploy:
    jobs:
      - maven/test:
          executor: default-executor
          pre-steps:
            - run:
                name: Install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.6.1
            - run:
                name: Wait for db
                command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # - heroku/deploy-via-git:
      #     force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
      #     requires:
      #       - build-and-test # only run deploy-via-git job if the build job has completed
      #     filters:
      #       branches:
      #         only: /.*-heroku-deploy/ # Delete this line
